import React from 'react';

const Fiche = () => {
    return (
        <div>
            <h1>Fihe</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur laboriosam eum dolorum et voluptates, vero mollitia nostrum illo incidunt quia hic atque, maiores modi obcaecati quas magni aperiam omnis iure quasi consectetur fuga, quae voluptate nam vitae! Voluptates quo officiis odio delectus et, doloremque, qui iste a beatae nostrum ipsa dolorum consequatur, deserunt ab ducimus atque nulla facere. Eum quibusdam praesentium numquam nisi hic ipsam veniam iure quasi similique inventore sunt quisquam, explicabo modi optio error eius magni ea sequi nostrum quam assumenda dolorem. Numquam animi quas eaque autem incidunt, soluta facilis, pariatur unde quibusdam placeat cupiditate similique obcaecati sequi nulla iure libero repudiandae perspiciatis alias qui est molestiae mollitia eligendi? Non repellat architecto obcaecati voluptatem ex tenetur facere optio minus, iure, nam cupiditate quo pariatur doloribus veniam, at eligendi magnam et accusamus. Eius ea ut cupiditate ipsum ad fuga hic magni optio rem! Accusantium vitae quisquam molestias eaque! Harum deleniti minima aut velit, magni adipisci ipsa quae provident amet deserunt? Voluptate cumque illo, nobis facilis id perferendis consectetur suscipit ipsam quam assumenda. Maiores, eum nobis deserunt repellendus ex iste vel consectetur, voluptates ea, illo sapiente dolorum maxime ipsa quod quo laboriosam eveniet. Accusamus consequatur, corrupti eaque quos perferendis suscipit perspiciatis ipsam fugiat numquam quibusdam, quod maxime excepturi nobis at ducimus enim voluptatum hic libero vero dolore. Doloremque delectus tenetur eius. Corrupti quam voluptas ratione, labore distinctio architecto eos unde, laborum repudiandae atque a magnam earum, delectus fugiat. Nobis earum qui omnis corrupti! Explicabo perferendis delectus voluptate, doloremque fuga ea veniam. Rerum rem doloribus facere excepturi natus architecto blanditiis dolorum dolor itaque repudiandae, sit repellat exercitationem dolore neque, sequi deserunt? Enim, nisi recusandae sequi unde ab ad sunt veritatis deleniti blanditiis vero quaerat facilis libero. Eum quasi voluptate itaque omnis veniam porro unde, expedita nulla. Ipsum rerum nemo dicta dolores expedita, optio doloremque eos reiciendis ipsa quae doloribus reprehenderit laudantium adipisci veniam repudiandae dolore modi animi iure libero impedit culpa quod quis. Omnis vero atque eaque facere inventore aspernatur velit? Accusamus ut asperiores consequatur unde ullam corrupti iure laboriosam sit dolorum nesciunt? Molestias voluptatibus vel, expedita sequi dolores maxime natus consequatur, adipisci cupiditate delectus, fugit sit optio inventore reiciendis vero officia nisi rerum necessitatibus ex! Error blanditiis, inventore ex dicta voluptates ipsum molestiae nulla a mollitia consectetur ratione saepe itaque atque, odit expedita distinctio necessitatibus rem eum voluptas! Placeat tempora consequuntur, iure voluptatem inventore sequi tempore deleniti et qui blanditiis.</p>
        </div>
    );
};

export default Fiche;